#!/bin/sh
set -eu

while read -r local_ref local_sha remote_ref remote_sha
do
  case "$remote_ref" in
    refs/heads/main|refs/heads/master)
      echo "Direct pushes to ${remote_ref#refs/heads/} are blocked. Merge through a PR." >&2
      exit 1
      ;;
  esac
done

